module4-task1
htmlacademy-nodejs/219791-kekstagram pull request #9
Opened 2018-10-10 22:09 UTC by GregoryAndrievskiy

2018-10-13 09:03 UTC, dean992008 requested changes

2018-10-13 09:03 UTC, dean992008 commented on commands/server.js
> +    const port = process.argv[3] ? process.argv[3] : 3000;
Нужно дополнительно проверить что номер порта это число.

2018-10-13 09:03 UTC, dean992008 commented on commands/server.js
> +          res.statusMessage = `OK`;
Ну нужно указывать статус равный статусу по умолчанию.

2018-10-13 09:03 UTC, dean992008 commented on commands/server.js
> +          res.writeHead(404, `Not Found`);
Вместо стороки лучше использовать обьект `http.STATUS_CODES`

2018-10-13 09:03 UTC, dean992008 commented on commands/server.js
> +    const server = http.createServer((req, res) => {
Передачу параметра я бы поменял на подписку на `EventEmiter`

2018-10-13 09:03 UTC, dean992008 commented on commands/server.js
> +      (async () => {
По адрессу `/` нужно возвращяться файл `/index.html`.

2018-10-13 09:03 UTC, dean992008 commented on commands/server.js
> +    const serverAddress = `http://${hostname}:${port}`;
Зачем сохранять в переменую? Можно сразу использовать внутри `listen`

2018-10-14 12:54 UTC, GregoryAndrievskiy commented on commands/server.js
> +    const server = http.createServer((req, res) => {
Речь идет о порте сервера?

2018-10-14 15:52 UTC, dean992008 commented on commands/server.js
> +    const server = http.createServer((req, res) => {
Здесь я имел виду что нужно вызвать `http.createServer` без параметров. А функцию обработчик вызвать `server.on('request', ...`. Кроме того у 1 одного сервера так может быть несколько обработчиков которые выполняется в порядке их установки.

2018-10-14 18:27 UTC, dean992008 approved these changes

2018-10-14 18:27 UTC, merged